name: 'dbt_bndes'
version: '1.0.0'
config-version: 2

profile: 'dbt_bndes_profile'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_bndes:
    staging:
      +materialized: view
    marts:
      +materialized: table
